import math

from google import genai
from google.genai import types

from app.core.config import settings
from app.core.constants import (
    EMBEDDING_DIMENSIONS,
    EMBEDDING_MODEL,
    TASK_TYPE_DOCUMENT,
    TASK_TYPE_QUERY,
)


class EmbeddingError(Exception):
    """Raised when an embedding cannot be generated by Gemini."""


_client: genai.Client | None = None


def _get_client() -> genai.Client:
    """Create the Gemini client once and reuse the same client."""
    global _client

    if _client is None:
        if not settings.GEMINI_API_KEY:
            raise EmbeddingError("GEMINI_API_KEY is not set in the .env file")
        _client = genai.Client(api_key=settings.GEMINI_API_KEY)

    return _client


def _normalise(vector: list[float]) -> list[float]:
    """Normalize the vector so that its length becomes 1."""
    length = math.sqrt(sum(value * value for value in vector))
    if length == 0:
        return vector
    return [value / length for value in vector]


def _embed_one(text: str, task_type: str) -> list[float]:
    """Generate an embedding for a single piece of text."""
    client = _get_client()

    try:
        response = client.models.embed_content(
            model=EMBEDDING_MODEL,
            contents=text,
            config=types.EmbedContentConfig(
                task_type=task_type,
                output_dimensionality=EMBEDDING_DIMENSIONS,
            ),
        )
    except Exception as exc:
        raise EmbeddingError(f"Gemini embedding generation failed: {exc}") from exc

    if not response.embeddings:
        raise EmbeddingError("Gemini returned an empty embedding")

    vector = list(response.embeddings[0].values)

    if len(vector) != EMBEDDING_DIMENSIONS:
        raise EmbeddingError(
            f"Expected {EMBEDDING_DIMENSIONS} numbers, but received {len(vector)}"
        )

    return _normalise(vector)


def embed_documents(texts: list[str]) -> list[list[float]]:
    """Generate embeddings for document chunks that will be stored."""
    return [_embed_one(text, TASK_TYPE_DOCUMENT) for text in texts]


def embed_query(text: str) -> list[float]:
    """Generate an embedding for a user question; used in Day 12."""
    return _embed_one(text, TASK_TYPE_QUERY)